### PR TITLE
Misc input fixes

### LINKED ISSUE #1864: Fix textbox in trade and liquidity windows
Unlimited characters doesn't seem nice

Screenshot 2023-10-07 at 4 07 47 PM

App crashes on hitting `delete` key

Screenshot 2023-10-07 at 4 09 18 PM

App crashes on reaching certain character limit

Screenshot 2023-10-07 at 4 09 34 PM

### PR DESCRIPTION
**Pull request by Robiquet**
closes #1864

### CODE REVIEW

File: components/markets/BuyFullSetForm.tsx [hunk 1]
```diff
@@ -59,10 +59,10 @@ const BuyFullSetForm = ({
     fee,
   } = useExtrinsic(
     () => {
-      if (isRpcSdk(sdk)) {
+      if (isRpcSdk(sdk) && amount && amount !== "") {
         return sdk.api.tx.predictionMarkets.buyCompleteSet(
```
Comment (robhyrk) [inline components/markets/BuyFullSetForm.tsx:63]: getting an error here when I type a large number: 

`Error: createType(Call):: Call: failed decoding predictionMarkets.buyCompleteSet:: Struct: failed on args: {"market_id":"Compact<u128>","amount":"Compact<u128>"}:: Struct: failed on amount: Compact<u128>:: u128: Input too large. Found input with 131 bits, expected 128`

File: components/markets/SellFullSetForm.tsx [hunk 2]
```diff
@@ -52,10 +52,10 @@ const SellFullSetForm = ({
     fee,
   } = useExtrinsic(
     () => {
-      if (isRpcSdk(sdk)) {
+      if (isRpcSdk(sdk) && amount && amount !== "") {
         return sdk.api.tx.predictionMarkets.sellCompleteSet(
```
Comment (robhyrk) [inline components/markets/SellFullSetForm.tsx:56]: getting the same error here as in the buy full set. 

Also, not sure if we want this behaviour but I'm able to type `e` within the input boxes. Assuming that's math related.

**Review by robhyrk — APPROVED** [review]
The issue #1864 also mentioned limiting characters in the input boxes. Not sure if that should be covered here or in another issue perhaps
