### PR TITLE
#887 Fix Modal Components Alignment

### LINKED ISSUE #887: Fix alignment of the ZTG Input and the paddings on the button
Fix alignment of the ZTG Input and the paddings on the button

image

### PR DESCRIPTION
**Pull request by robhyrk**
closes #887

### CODE REVIEW

File: components/markets/MarketsList.tsx [hunk 1]
```diff
@@ -100,6 +100,7 @@ const MarketsList = observer(({ className = "" }: MarketsListProps) => {
           const volume = market.pool?.volume ?? 0;
           const scalarType = market.scalarType as ScalarRangeType;
           const stat = stats?.find((s) => s.marketId === market.marketId);
+          // console.log(market.question, stat?.liquidity);
```
Comment (yornaath) [inline components/markets/MarketsList.tsx:103]: Can remove this prob

File: lib/hooks/queries/useInfiniteMarkets.ts [hunk 2]
```diff
@@ -78,14 +77,14 @@ export const useInfiniteMarkets = (
     const statuses = getFilterValuesByType(filters, "status") as MarketStatus[];
     const tags = getFilterValuesByType(filters, "tag");
     const currencies = getFilterValuesByType(filters, "currency");
-
+    console.log(statuses);
```
Comment (yornaath) [inline lib/hooks/queries/useInfiniteMarkets.ts:80]: Remove logging

File: lib/hooks/queries/useInfiniteMarkets.ts [hunk 3]
```diff
@@ -97,7 +96,7 @@ export const useInfiniteMarkets = (
       limit: limit,
       order: orderByMap[orderBy],
     });
-
+    console.log(markets);
```
Comment (yornaath) [inline lib/hooks/queries/useInfiniteMarkets.ts:99]: remove logging

File: lib/hooks/queries/useInfiniteMarkets.ts [hunk 4]
```diff
@@ -78,14 +77,14 @@ export const useInfiniteMarkets = (
...
-
+    console.log(statuses);
     const markets: Market<IndexerContext>[] = await sdk.model.markets.list({
       where: {
         categories_isNull: false,
         status_not_in: [MarketStatus.Destroyed],
         status_in: statuses.length === 0 ? undefined : statuses,
         tags_containsAny: tags.length === 0 ? undefined : tags,
-        pool_isNull: withLiquidityOnly ? false : undefined,
+        pool_isNull: true,
```
Comment (yornaath) [inline lib/hooks/queries/useInfiniteMarkets.ts:87]: I think this filters for only markets that has no pool? Is that what we want here?

**Review by yornaath — CHANGES_REQUESTED** [review]

**Review by yornaath — APPROVED** [review]
LGTM
