### PR TITLE
Price fetching cache

### LINKED ISSUE #1697: Foreign asset price fetching
Sometimes price fetching is failing and making the page crash. We should make the code more robust and investigate better ways to fetch prices. Maybe can use edge functions to cache

### PR DESCRIPTION
**Pull request by Robiquet**
closes #1697

### CODE REVIEW

File: pages/api/usd-price-edge.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import { NextResponse } from "next/server";
```
Comment (yornaath) [inline pages/api/usd-price-edge.ts:1]: Maybe remove this file if edge didnt work for this?
