### PR TITLE
Map error type to message

### LINKED ISSUE #1763: Incorrect error message when connecting wallet
image

### PR DESCRIPTION
**Pull request by Robiquet**
closes #1763

### CODE REVIEW

File: components/account/WalletSelect.tsx [hunk 1]
```diff
@@ -63,9 +63,10 @@ const WalletSelect = () => {
               )}
               {hasError && (
                 <div className="text-vermilion ml-auto  text-ztg-12-120 w-ztg-275">
-                  {error.type === "NoAccounts"
```
Comment (yornaath) [inline components/account/WalletSelect.tsx:66]: What does this actually change? Since error type should only be one of two types it seems like the old code should cover all cases?

Comment (Robiquet) [reply components/account/WalletSelect.tsx:66]: I suspect the types are probably wrong and not all errors are accounted for. Even so, I don't think the previous code is good practice as it assumes that there will only ever be 2 error messages

**Review by yornaath — APPROVED** [review]
