### PR TITLE
Leaderboard fix + breakdown

### LINKED ISSUE #2256: Highlight computations for leaderboard
Owing to overload of debugging leaderboard requests on @Robiquet, I agree that it would make sense to add more visibility to calculations for leaderboard on the front end. This should save us some time, build more trust and overall acts as a support to future requests.

### PR DESCRIPTION
**Pull request by Robiquet**
closes #2256

### CODE REVIEW

File: pages/leaderboard/[period].tsx [hunk 1]
```diff
@@ -416,6 +412,14 @@ export async function getStaticProps({ params }) {
         );
 
         const usdProfitLoss = diff.mul(marketEndBaseAssetPrice ?? 0);
+
+        marketsSummary.push({
+          question: market.question!,
```
Comment (robhyrk) [inline pages/leaderboard/[period].tsx:417]: Is it possible to do a check for `market.question` before this point?

**Review by robhyrk — CHANGES_REQUESTED** [review]

**Review by robhyrk — APPROVED** [review]
