### PR TITLE
Deposit Page: Fix Mobile Styles

### LINKED ISSUE #1771: Spacing issues on deposit and create account page
Screenshot 2023-09-05 at 5 34 37 PM

### PR DESCRIPTION
**Pull request by robhyrk**
closes #1771

### CODE REVIEW

**Review by Robiquet — APPROVED** [review]

File: pages/deposit.tsx [hunk 1]
```diff
@@ -86,7 +86,7 @@ const UsdtIcon = (props: SVGProps<SVGSVGElement>) => (
 );
 
 const DepositMethodItems = ["buy", "deposit"] as const;
-type DepositMethod = typeof DepositMethodItems[number];
+type DepositMethod = (typeof DepositMethodItems)[number];
```
Comment (Robiquet) [inline pages/deposit.tsx:89]: Is this purely a formatting change?

Comment (robhyrk) [reply pages/deposit.tsx:89]: yes, I think prettier automatically applied this
